### ISSUE TITLE
Ошибка ImportError: No module named xmpp

### ISSUE THREAD

**Issue by opiums9** [zinid/mrim#7]
Здравствуйте, скачал ваш транспорт, решил проверить, но не могу запустить из за ошибки:
`Traceback (most recent call last):
  File "C:\Python27\mrim2\src\mrim.py", line 54, in <module>
    import init
  File "C:\Python27\mrim2\src\init.py", line 81, in <module>
    import xmpp
ImportError: No module named xmpp`
Скажите пожалуйста, как это исправить?
**ОС: Win 7 Ultimate**

**P.S.** Запускаю батником **C:\Python27\mrim2>src\mrim.py -c mrim.conf**

**Comment by shizeeg** [comment]
судя по официальной инструкции https://github.com/zinid/mrim/blob/master/INSTALL#L19 у вас не установлена `xmpppy`. В *nix системах устанавливается из репозитария или коммандой:

`$ pip install xmppy`

в Windows без понятия как, но думаю похожим образом.

**Comment by opiums9** [comment]
Установил, но всё таки что то не пошло...

`17/01/17-17:58:08 Connecting to XMPP server
Traceback (most recent call last):
  File "C:\Python27\mrim2\src\init.py", line 134, in start
    xmpp_con.run()
  File "C:\Python27\mrim2\src\transport.py", line 45, in run
    self.start(self.server, self.port, self.name, self.password)
  File "C:\Python27\mrim2\src\gw.py", line 16, in start
    self.connect((server, port))
  File "C:\Python27\lib\xmpp\client.py", line 272, in connect
    CommonClient.connect(self,server=server,proxy=proxy)
  File "C:\Python27\lib\xmpp\client.py", line 179, in connect
    if not self.Process(1): return
  File "C:\Python27\lib\xmpp\dispatcher.py", line 302, in dispatch
    handler['func'](session,stanza)
  File "C:\Python27\lib\xmpp\dispatcher.py", line 214, in streamErrorHandler
    raise exc((name,text))
Conflict: (u'conflict', '')
17/01/17-17:58:08 Connection to server lost
17/01/17-17:58:08 Trying to reconnect over 5 seconds`

**Comment by opiums9** [comment]
Прошу прощения, было исправлено, созданием папки "profile", но...
Транспорт работает, я нашёл подобный транспорт в интернете, такая же проблема, отписываюсь...
Спустя примерно минуту происходит обрыв связи, и переподключение, которое не происходит...
Как это можно исправить?

`17/01/17-18:04:10 [opiums29@mail.ru] Connecting to 217.69.141.159:2042
17/01/17-18:04:10 [opiums29@mail.ru] Successfully connected
17/01/17-18:04:10 [opiums29@mail.ru] Sending credentials
17/01/17-18:04:10 [opiums29@mail.ru] Authorization successfull: logged in
17/01/17-18:04:55 [opiums29@mail.ru] Connection error (217.69.141.159): Connecti
on reset by peer
17/01/17-18:04:55 [opiums29@mail.ru] Reconnect over 3 seconds`

**P.S.** Проблема проявляется только на Windows. Jabber сервер Openfire 4.0.3

- Не ведётся лог, хотя в конфиге он есть

**Comment by jihadismail8** [comment]
Здравствуйте opiums9
созданием папки "profile"  где ??

**Comment by opiums9** [comment]
jihadismail8, там где она указана в конфиге, в директории, где расположен транспорт

**Comment by jihadismail8** [comment]
[profile]
type = xml
dir = /var/spool/mrim

тут  ?

**Comment by opiums9** [comment]
да, но я изменил у себя директорию до:

[profile]
type = xml
dir = profile

**Comment by opiums9** [comment]
если в винде - то достаточно адреса до папки... если в юниксе/линухе, то нужен полный путь я так понял

**Comment by jihadismail8** [comment]
Пожалуйста, пришлите мне ссылку на тот транспорт, который Вы нашли в интернете.Добавьте меня в Skype.    jihad.ismail.8
